spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: AuthenticationApp
          uri: lb://AuthenticationApp
          predicates:
            - Path=/user/**
        - id: websocket-server
          uri: lb://websocket-server
          predicates:
            - Path=/ws/**
